# Generated by Django 5.1.7 on 2025-05-07 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hoe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=20, unique=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('product_description', models.TextField(blank=True)),
                ('product_image', models.ImageField(blank=True, upload_to='product_images')),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('product_stock', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Produce',
                'verbose_name_plural': 'Produce',
                'db_table': 'produce',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['branch', '-date']},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='type_of_stock',
            new_name='type_of_produce',
        ),
        migrations.RemoveField(
            model_name='creditsale',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_saleagent',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='amount_paid',
            field=models.IntegerField(default=10000, max_length=10),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='balance',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+2567XXXXXXXX'.", regex='^\\+?256[0-9]{9,15}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_director',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_salesagent',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+2567XXXXXXXX'.", regex='^\\+?256[0-9]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_details', to='happy_hoe.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.IntegerField(blank=True, default=1500, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Mobile Money', 'Mobile Money')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='entry_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_sales', to='happy_hoe.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock', to='happy_hoe.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='happy_hoe.branch'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'date'], name='happy_hoe_s_branch__79989e_idx'),
        ),
        migrations.AddField(
            model_name='produce',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happy_hoe.branch'),
        ),
    ]
