# Generated by Django 5.1.7 on 2025-04-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_saleagent',
            new_name='is_salesagent',
        ),
    ]
