# Generated by Django 5.1.7 on 2025-05-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hoe', '0002_rename_is_saleagent_userprofile_is_salesagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='branch_name',
            field=models.CharField(default='Maganjo', max_length=20, verbose_name=(('Maganjo', 'Maganjo'), ('Matugga', 'Matugga'))),
        ),
    ]
