# Generated by Django 5.1.7 on 2025-05-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hoe', '0004_category_description_alter_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('opening_date', models.DateField()),
                ('location', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, unique=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(blank=True, upload_to='product_images')),
                ('product_category', models.CharField(max_length=100)),
                ('product_stock', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Produce',
                'verbose_name_plural': 'Produce',
                'db_table': 'produce',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='happy_hoe.branch'),
        ),
    ]
