# Generated by Django 5.1.7 on 2025-05-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hoe', '0006_alter_userprofile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='happy_hoe.branch'),
        ),
    ]
