# Generated by Django 5.1.7 on 2025-05-05 12:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hoe', '0007_alter_branch_id_alter_userprofile_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['branch', '-date']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['branch', 'product_name']},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='opening_date',
        ),
        migrations.RemoveField(
            model_name='creditsale',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='type_of_stock',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='creditsale',
            name='amount_paid',
            field=models.IntegerField(default=10000, max_length=10),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='balance',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creditsale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='produce',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='happy_hoe.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_sales', to='happy_hoe.branch'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_stock', to='happy_hoe.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier_contact',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+2567XXXXXXXX'.", regex='^\\+?256[0-9]{9,15}$')]),
        ),
        migrations.AddField(
            model_name='stock',
            name='type_of_produce',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_director',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+2567XXXXXXXX'.", regex='^\\+?256[0-9]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creditsale',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_details', to='happy_hoe.sale'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='product_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produce',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produce',
            name='product_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='produce',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produce',
            name='product_stock',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.IntegerField(blank=True, default=1500, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Mobile Money', 'Mobile Money')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_of_stock',
            field=models.DecimalField(decimal_places=0, default=1000000, max_digits=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='entry_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issued_quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.CharField(choices=[('beans', 'beans'), ('soybeans', 'soybeans'), ('gnuts', 'gnuts'), ('maize', 'maize'), ('cowpeas', 'cowpeas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_cost',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_salesagent',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'date'], name='happy_hoe_s_branch__79989e_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['branch', 'product_name'], name='happy_hoe_s_branch__00707a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('branch', 'product_name'), name='unique_product_per_branch'),
        ),
    ]
